/**
 * @file SyncController.hpp
 * @brief SyncController — generated by scripts/new-endpoint.sh.
 */

#pragma once

#include <drogon/HttpController.h>
#include <drogon/drogon.h>

#include <nlohmann/json.hpp>

// Controllers must NOT include api/Api.hpp (it includes the controllers — that
// would cycle). Pull only the small shared helpers.
#include "api/Guards.hpp"        // API_REQUIRE_ADMIN / API_REQUIRE_PRINCIPAL
#include "api/RequestUtils.hpp"  // parse_int / parse_page_params / is_valid_uuid
#include "api/Validation.hpp"
#include "utils/ErrorResponse.hpp"  // Response::ok / ErrorResponse::*

namespace Api {

using namespace drogon;
using json = nlohmann::json;

class SyncController : public HttpController<SyncController> {
public:
    METHOD_LIST_BEGIN
    ADD_METHOD_TO(SyncController::enqueue, "/api/v1/sync", Post);
    ADD_METHOD_TO(SyncController::status, "/api/v1/sync/{id}", Get);
    METHOD_LIST_END

    void enqueue(const HttpRequestPtr& /*req*/, std::function<void(const HttpResponsePtr&)>&& callback) {
        json response = {{"message", "SyncController::enqueue — TODO"}};
        callback(Response::ok(response));
    }

    void status(const HttpRequestPtr& /*req*/,
                std::function<void(const HttpResponsePtr&)>&& callback,
                const std::string& id) {
        json response = {{"message", "SyncController::status — TODO"}, {"id", id}};
        callback(Response::ok(response));
    }
};

}  // namespace Api
