/**
 * @file XiaomiController.hpp
 * @brief XiaomiController — generated by scripts/new-endpoint.sh.
 */

#pragma once

#include <drogon/HttpController.h>
#include <drogon/drogon.h>

#include <nlohmann/json.hpp>

// Controllers must NOT include api/Api.hpp (it includes the controllers — that
// would cycle). Pull only the small shared helpers.
#include "api/Guards.hpp"        // API_REQUIRE_ADMIN / API_REQUIRE_PRINCIPAL
#include "api/RequestUtils.hpp"  // parse_int / parse_page_params / is_valid_uuid
#include "api/Validation.hpp"
#include "utils/ErrorResponse.hpp"  // Response::ok / ErrorResponse::*

namespace Api {

using namespace drogon;
using json = nlohmann::json;

class XiaomiController : public HttpController<XiaomiController> {
public:
    METHOD_LIST_BEGIN
    ADD_METHOD_TO(XiaomiController::probe, "/api/v1/xiaomi/probe", Get);
    METHOD_LIST_END

    void probe(const HttpRequestPtr& req, std::function<void(const HttpResponsePtr&)>&& callback) {
        json response = {{"message", "XiaomiController::probe — TODO"}};
        callback(Response::ok(response));
    }
};

}  // namespace Api
