#!/usr/bin/env bash
#
# Scaffold a feature-module master switch end to end, following the content
# module's on/off pattern (Core::content_enabled() + CONTENT_ENABLED):
#
#   config/config.json + config.sample.json  {"<name>": {"enabled": "${<NAME>_ENABLED:-false}"}}
#   src/core/Modules.hpp                     Core::<name>_enabled() beside content_enabled()
#   docker/docker-compose.yml                <NAME>_ENABLED on the app service
#   helm/mi-fitness-api                             values key + configmap fragment + deployment env
#   helm/mi-fitness-api-worker                          values key + configmap fragment + deployment env
#   docs/CONFIG.md                           a "<Name> module" table section
#   src/<name>/<Name>.hpp                    empty namespace header for the module's code
#
# The switch ships OFF everywhere (same as CONTENT_ENABLED / JOBS_ENABLED):
# routes stay statically registered; handlers consult Core::<name>_enabled()
# per request and 404 while the module is off (see PostsController).
#
# Downstream motivation: the site fork's billing module needed hand-wiring in
# 7+ infra spots (config, compose, both charts, docs) — every one forgettable,
# several forgotten on the first pass. This script owns that checklist.
#
# Safe to re-run: every patch is anchor-checked, verified after insertion, and
# skipped when already present.
#
# Usage:
#   ./scripts/new-module.sh <name>       # lower snake_case, e.g. billing
set -euo pipefail

die() {
    echo "ERROR: $*" >&2
    exit 1
}

if [[ $# -ne 1 || "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
    echo "Usage: $0 <name>   (lower snake_case, e.g. billing)" >&2
    exit 2
fi

NAME="$1"
[[ "$NAME" =~ ^[a-z][a-z0-9_]*$ ]] || die "module name must be lower snake_case [a-z0-9_], got '$NAME'"

# Reserved: existing top-level config blocks — a module by these names would
# collide with (or shadow) an existing subsystem's config.
case "$NAME" in
app | server | logging | observability | database | cache | messaging | api | docs | security | auth | cors | mail | storage | rate_limit | idempotency | jobs | content | worker | shutdown)
    die "'$NAME' is a reserved top-level config key — pick another module name"
    ;;
esac

NAME_UPPER="$(printf '%s' "$NAME" | tr '[:lower:]' '[:upper:]')"
PASCAL=""
for part in ${NAME//_/ }; do
    # PascalCase each part (portable: bash 3.2 lacks ${part^}).
    first="$(printf '%s' "$part" | cut -c1 | tr '[:lower:]' '[:upper:]')"
    rest="$(printf '%s' "$part" | cut -c2-)"
    PASCAL+="${first}${rest}"
done

ROOT="$(cd "$(dirname "$0")/.." && pwd)"

# ── 1. config/config.json + config/config.sample.json ────────────────────
patch_config() {
    local f="$1"
    [[ -f "$f" ]] || die "$f not found"
    if grep -qF "\"${NAME}\": {" "$f"; then
        echo "==> $(basename "$f") already has a \"${NAME}\" block — skipped"
        return 0
    fi
    grep -qF '  "worker": {' "$f" || die "anchor '\"worker\": {' not found in $f — add the ${NAME} block by hand"
    awk -v name="$NAME" -v upper="$NAME_UPPER" '
        /^  "worker": \{/ && !done {
            print "  \"" name "\": {"
            print "    \"enabled\": \"${" upper "_ENABLED:-false}\""
            print "  },"
            done=1
        }
        { print }
    ' "$f" >"$f.tmp" && mv "$f.tmp" "$f"
    grep -qF "\"${NAME}\": {" "$f" || die "failed to insert the ${NAME} block into $f"
    echo "==> Patched $f"
}
patch_config "$ROOT/config/config.json"
patch_config "$ROOT/config/config.sample.json"
# config/config.production.json is deliberately NOT touched — modules ship
# gated off in prod until you opt in there explicitly (make prod-check).

# ── 2. Core::<name>_enabled() ────────────────────────────────────────────
# The switch lives in core/Modules.hpp (NOT Core.hpp): controllers include
# only that tiny header, so a new module switch doesn't drag the whole
# composition root into every controller TU.
CORE="$ROOT/src/core/Modules.hpp"
if grep -qF "inline bool ${NAME}_enabled()" "$CORE"; then
    echo "==> Core::${NAME}_enabled() already exists — skipped"
else
    grep -qF '}  // namespace Core' "$CORE" || die "anchor '}  // namespace Core' not found in $CORE"
    awk -v name="$NAME" -v upper="$NAME_UPPER" -v pascal="$PASCAL" '
        /^\}  \/\/ namespace Core$/ && !done {
            print "/// " pascal " module master switch — generated by scripts/new-module.sh; same"
            print "/// pattern (and same Config::is_initialized() guard) as content_enabled()"
            print "/// above: routes are statically registered, handlers consult this"
            print "/// per-request and 404 while the module is off."
            print "inline bool " name "_enabled() {"
            print "    if (!Config::is_initialized())"
            print "        return false;"
            print "    return Config::get().get<bool>(\"" name ".enabled\", \"" upper "_ENABLED\", false);"
            print "}"
            print ""
            done=1
        }
        { print }
    ' "$CORE" >"$CORE.tmp" && mv "$CORE.tmp" "$CORE"
    grep -qF "inline bool ${NAME}_enabled()" "$CORE" || die "failed to insert ${NAME}_enabled() into $CORE"
    echo "==> Added Core::${NAME}_enabled() to $CORE"
fi

# ── 3. docker-compose: env on the app service (same slot as CONTENT_ENABLED) ─
COMPOSE="$ROOT/docker/docker-compose.yml"
if grep -qF "${NAME_UPPER}_ENABLED:" "$COMPOSE"; then
    echo "==> docker-compose already wires ${NAME_UPPER}_ENABLED — skipped"
else
    grep -qF 'CONTENT_ENABLED: ${CONTENT_ENABLED:-false}' "$COMPOSE" || die "CONTENT_ENABLED anchor not found in $COMPOSE"
    awk -v upper="$NAME_UPPER" '
        { print }
        /^      CONTENT_ENABLED: \$\{CONTENT_ENABLED:-false\}$/ && !done {
            print "      " upper "_ENABLED: ${" upper "_ENABLED:-false}"
            done=1
        }
    ' "$COMPOSE" >"$COMPOSE.tmp" && mv "$COMPOSE.tmp" "$COMPOSE"
    grep -qF "${NAME_UPPER}_ENABLED:" "$COMPOSE" || die "failed to insert ${NAME_UPPER}_ENABLED into $COMPOSE"
    echo "==> Patched $COMPOSE (app service)"
fi

# ── 4a. helm/mi-fitness-api/values.yaml ─────────────────────────────────────────
API_VALUES="$ROOT/helm/mi-fitness-api/values.yaml"
if grep -qE "^${NAME}:" "$API_VALUES"; then
    echo "==> mi-fitness-api values already has a '${NAME}:' block — skipped"
else
    grep -qE '^content:$' "$API_VALUES" || die "anchor 'content:' not found in $API_VALUES"
    awk -v name="$NAME" -v upper="$NAME_UPPER" '
        { print }
        /^content:$/ { in_content=1 }
        in_content && /^  enabled: false$/ && !done {
            print ""
            print "# ---------------------------------------------------------------"
            print "# " name " module — generated by scripts/new-module.sh; same on/off"
            print "# pattern as Content above. Env var set: " upper "_ENABLED"
            print "# ---------------------------------------------------------------"
            print name ":"
            print "  enabled: false"
            done=1
            in_content=0
        }
    ' "$API_VALUES" >"$API_VALUES.tmp" && mv "$API_VALUES.tmp" "$API_VALUES"
    grep -qE "^${NAME}:" "$API_VALUES" || die "failed to insert '${NAME}:' into $API_VALUES"
    echo "==> Patched $API_VALUES"
fi

# ── 4b. helm/mi-fitness-api/templates/deployment.yaml ───────────────────────────
API_DEPLOY="$ROOT/helm/mi-fitness-api/templates/deployment.yaml"
if grep -qF "name: ${NAME_UPPER}_ENABLED" "$API_DEPLOY"; then
    echo "==> mi-fitness-api deployment already wires ${NAME_UPPER}_ENABLED — skipped"
else
    grep -qF 'value: {{ .Values.content.enabled | quote }}' "$API_DEPLOY" || die "content.enabled anchor not found in $API_DEPLOY"
    awk -v name="$NAME" -v upper="$NAME_UPPER" '
        { print }
        /^              value: \{\{ \.Values\.content\.enabled \| quote \}\}$/ && !done {
            print "            # " name " module — generated by scripts/new-module.sh"
            print "            - name: " upper "_ENABLED"
            print "              value: {{ .Values." name ".enabled | quote }}"
            done=1
        }
    ' "$API_DEPLOY" >"$API_DEPLOY.tmp" && mv "$API_DEPLOY.tmp" "$API_DEPLOY"
    grep -qF "name: ${NAME_UPPER}_ENABLED" "$API_DEPLOY" || die "failed to insert ${NAME_UPPER}_ENABLED into $API_DEPLOY"
    echo "==> Patched $API_DEPLOY"
fi

# ── 4c. helm/mi-fitness-api/templates/configmap.yaml ────────────────────────────
API_CM="$ROOT/helm/mi-fitness-api/templates/configmap.yaml"
if grep -qF "\"${NAME}\": {" "$API_CM"; then
    echo "==> mi-fitness-api configmap already has a \"${NAME}\" block — skipped"
else
    grep -qF '      "rate_limit": {' "$API_CM" || die "anchor '\"rate_limit\": {' not found in $API_CM"
    awk -v name="$NAME" '
        /^      "rate_limit": \{$/ && !done {
            print "      \"" name "\": {"
            print "        \"enabled\": {{ .Values." name ".enabled }}"
            print "      },"
            done=1
        }
        { print }
    ' "$API_CM" >"$API_CM.tmp" && mv "$API_CM.tmp" "$API_CM"
    grep -qF "\"${NAME}\": {" "$API_CM" || die "failed to insert the ${NAME} block into $API_CM"
    echo "==> Patched $API_CM"
fi

# ── 5a. helm/mi-fitness-api-worker/values.yaml ──────────────────────────────────────
WRK_VALUES="$ROOT/helm/mi-fitness-api-worker/values.yaml"
if grep -qE "^${NAME}:" "$WRK_VALUES"; then
    echo "==> mi-fitness-api-worker values already has a '${NAME}:' block — skipped"
else
    grep -qE '^  maxRetries: 3$' "$WRK_VALUES" || die "jobs.maxRetries anchor not found in $WRK_VALUES"
    awk -v name="$NAME" -v upper="$NAME_UPPER" '
        { print }
        /^  maxRetries: 3$/ && !done {
            print ""
            print "# ---------------------------------------------------------------"
            print "# " name " module — generated by scripts/new-module.sh; keep in sync"
            print "# with the mi-fitness-api chart. Env var set: " upper "_ENABLED"
            print "# ---------------------------------------------------------------"
            print name ":"
            print "  enabled: false"
            done=1
        }
    ' "$WRK_VALUES" >"$WRK_VALUES.tmp" && mv "$WRK_VALUES.tmp" "$WRK_VALUES"
    grep -qE "^${NAME}:" "$WRK_VALUES" || die "failed to insert '${NAME}:' into $WRK_VALUES"
    echo "==> Patched $WRK_VALUES"
fi

# ── 5b. helm/mi-fitness-api-worker/templates/deployment.yaml ────────────────────────
WRK_DEPLOY="$ROOT/helm/mi-fitness-api-worker/templates/deployment.yaml"
if grep -qF "name: ${NAME_UPPER}_ENABLED" "$WRK_DEPLOY"; then
    echo "==> mi-fitness-api-worker deployment already wires ${NAME_UPPER}_ENABLED — skipped"
else
    grep -qE '^            # Worker$' "$WRK_DEPLOY" || die "'# Worker' anchor not found in $WRK_DEPLOY"
    awk -v name="$NAME" -v upper="$NAME_UPPER" '
        /^            # Worker$/ && !done {
            print "            # " name " module — generated by scripts/new-module.sh"
            print "            - name: " upper "_ENABLED"
            print "              value: {{ .Values." name ".enabled | quote }}"
            done=1
        }
        { print }
    ' "$WRK_DEPLOY" >"$WRK_DEPLOY.tmp" && mv "$WRK_DEPLOY.tmp" "$WRK_DEPLOY"
    grep -qF "name: ${NAME_UPPER}_ENABLED" "$WRK_DEPLOY" || die "failed to insert ${NAME_UPPER}_ENABLED into $WRK_DEPLOY"
    echo "==> Patched $WRK_DEPLOY"
fi

# ── 5c. helm/mi-fitness-api-worker/templates/configmap.yaml ─────────────────────────
WRK_CM="$ROOT/helm/mi-fitness-api-worker/templates/configmap.yaml"
if grep -qF "\"${NAME}\": {" "$WRK_CM"; then
    echo "==> mi-fitness-api-worker configmap already has a \"${NAME}\" block — skipped"
else
    grep -qF '      "worker": {' "$WRK_CM" || die "anchor '\"worker\": {' not found in $WRK_CM"
    awk -v name="$NAME" '
        /^      "worker": \{$/ && !done {
            print "      \"" name "\": {"
            print "        \"enabled\": {{ .Values." name ".enabled }}"
            print "      },"
            done=1
        }
        { print }
    ' "$WRK_CM" >"$WRK_CM.tmp" && mv "$WRK_CM.tmp" "$WRK_CM"
    grep -qF "\"${NAME}\": {" "$WRK_CM" || die "failed to insert the ${NAME} block into $WRK_CM"
    echo "==> Patched $WRK_CM"
fi

# ── 6. docs/CONFIG.md ────────────────────────────────────────────────────
CONFIG_MD="$ROOT/docs/CONFIG.md"
if grep -qF "\`${NAME_UPPER}_ENABLED\`" "$CONFIG_MD"; then
    echo "==> docs/CONFIG.md already documents ${NAME_UPPER}_ENABLED — skipped"
else
    grep -qF '## Mail (SMTP)' "$CONFIG_MD" || die "anchor '## Mail (SMTP)' not found in $CONFIG_MD"
    awk -v name="$NAME" -v upper="$NAME_UPPER" -v pascal="$PASCAL" '
        $0 == "## Mail (SMTP)" && !done {
            print "## " pascal " module"
            print ""
            print "| Env | JSON key | Type | Default | Notes |"
            print "|---|---|---|---|---|"
            print "| `" upper "_ENABLED` | `" name ".enabled` | bool | `false` | Master switch for the " name " module (`Core::" name "_enabled()`) — same on/off pattern as `CONTENT_ENABLED`; routes stay registered, handlers 404 while off. Generated by `scripts/new-module.sh`. |"
            print ""
            done=1
        }
        { print }
    ' "$CONFIG_MD" >"$CONFIG_MD.tmp" && mv "$CONFIG_MD.tmp" "$CONFIG_MD"
    grep -qF "\`${NAME_UPPER}_ENABLED\`" "$CONFIG_MD" || die "failed to insert the ${NAME} section into $CONFIG_MD"
    echo "==> Patched $CONFIG_MD"
fi

# ── 7. Module namespace header ───────────────────────────────────────────
MOD_DIR="$ROOT/src/${NAME}"
MOD_HPP="$MOD_DIR/${PASCAL}.hpp"
if [[ -e "$MOD_HPP" ]]; then
    echo "==> $MOD_HPP already exists — skipped"
else
    mkdir -p "$MOD_DIR"
    cat >"$MOD_HPP" <<EOF
/**
 * @file ${PASCAL}.hpp
 * @brief ${PASCAL} module — generated by scripts/new-module.sh.
 * @details Module code lives under this namespace (header-only, ADR 0003).
 *          The master switch is Core::${NAME}_enabled() (config key
 *          "${NAME}.enabled" / env ${NAME_UPPER}_ENABLED, off by default).
 *          Gate every HTTP handler of this module on its FIRST line, before
 *          any auth guard — same idiom as PostsController:
 *
 *              if (!Core::${NAME}_enabled()) {
 *                  callback(ErrorResponse::not_found("${NAME}"));
 *                  return;
 *              }
 */

#pragma once

namespace ${PASCAL} {

// Module implementation goes here.

}  // namespace ${PASCAL}
EOF
    echo "==> Created $MOD_HPP"
fi

# ── 8. What's next ───────────────────────────────────────────────────────
cat <<EOF

==> Module '${NAME}' scaffolded. Next steps:
  1. Endpoints:  ./scripts/new-endpoint.sh ${PASCAL}Controller Get /api/v1/${NAME} --with-test
  2. In every handler of the module, FIRST line (before auth guards), as in
     PostsController:
         if (!Core::${NAME}_enabled()) {
             callback(ErrorResponse::not_found("${NAME}"));
             return;
         }
  3. Auth-public routes of the module go into api.public_paths_extra
     (ADDITIVE) — never by overriding api.public_paths.
  4. Enable locally:  ${NAME_UPPER}_ENABLED=true make up
     Enable in helm:  --set ${NAME}.enabled=true (both charts if the worker
     needs it).
  5. Unit-test the guard (see tests/unit/test_module_guards.cpp for the
     pattern) and run the gate sequence from CLAUDE.md before pushing.
EOF
