/**
 * @file Billing.hpp
 * @brief Billing module — generated by scripts/new-module.sh.
 * @details Module code lives under this namespace (declarations in .hpp,
 *          bodies in paired .cpp compiled into app_core — ADR 0003 as
 *          amended 2026-08-22):
 *          - src/billing/Wallet.hpp — the credit ledger's ONLY writer
 *            (credit_capture / refund_capture / adjust / balance_of / history);
 *          - src/billing/PayPalClient.hpp — provider client + the module's
 *            initialize()/install_for_testing()/reset_for_testing() seam;
 *          - src/domain/Billing.hpp + src/repositories/BillingRepository.hpp /
 *            BillingMetricsRepository.hpp — rows and SQL.
 *          The master switch is Core::billing_enabled() (config key
 *          "billing.enabled" / env BILLING_ENABLED, off by default).
 *          Core::initialize() calls Billing::initialize() so an enabled
 *          module with missing PayPal credentials fails at boot, not on the
 *          first request. Gate every HTTP handler of this module on its
 *          FIRST line, before any auth guard — the standard module idiom:
 *
 *              if (!Core::billing_enabled()) {
 *                  callback(ErrorResponse::not_found("billing"));
 *                  return;
 *              }
 */

#pragma once

#include "billing/PayPalClient.hpp"
#include "billing/Wallet.hpp"

namespace Billing {

// Umbrella header only — the module's implementation lives in the headers
// included above.

}  // namespace Billing
